services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=usuarios
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permite que o container acesse o localhost
    depends_on:
      - postgres  # Se necessário, ajuste as dependências conforme seu cenário

volumes:
  postgres_data:
  jenkins_home:
