pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "hexagonal:${env.BUILD_ID}"
        DOCKER_REPO = "riosberg/hexagonal"
    }
    stages {
        stage('Build Docker Image') {
            steps {
               script {
                dockerapp = docker.build("riosberg/hexagonal:${env.BUILD_ID}", "-f Dockerfile")
               }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", 'dockerhub') {
                        dockerapp.push("latest")
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
         stage('Deploy no Kubernets') {
            steps {
                sh 'echo "Executando o comando kubeclt apply"'
            }
        }
    }
}
